services:
  - type: web
    name: carulla
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    buildFilter:
      paths:
        - build.sh
        - requirements.txt
        - app.py
        - render.yaml
